### PR TITLE
Milestone 10: authorizations with cancancan

### PR DESCRIPTION
**Pull request by ITurres**
## Pull Request Summary for Milestone 10 Completion

- [x] All [requirements](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_add_authorization.md) completed.

---

#### `/app/models/ability.rb`

- @ITurres: I have added the `Ability` class to define the user permissions.
- This will allow the user to only edit and delete their own posts and comments.
- It will also allow user's with the `admin` role to edit and delete any/all post or comment.

#### `/db/migrate/20231214152949_add_role_to_user.rb`

- @ITurres: I have added the `role` column to the `users` table.

---

#### `/Gemfile` **and** `/Gemfile.lock`

- @ITurres: I have added the `cancancan` gem to the `Gemfile` and ran `bundle install`.

#### `/README.md`

- @ITurres: I have the highlighted gems at the 'tech-stack' section.
- @ITurres: check complete the 'authorization' task.

#### `/app/controllers/posts_controller.rb`

- @ITurres: With the `load_and_authorize_resource` and `destroy` action, now we can delete posts.

#### `/app/controllers/comments_controller.rb`

- @demesameneshoa: With the `destroy` action, now we can delete comments.

#### `/app/models/post.rb`

- @ITurres: the `update_posts_counter` has been modified to accept a status of `increment` or `decrement` and update the `posts_count` accordingly.

#### `/app/models/user.rb`

- @ITurres: All relationships with `posts`, `comments` and `likes` have been modified to `dependent: :destroy` to delete all associated posts and comments when a user is deleted.

#### `/app/views/posts/show.html.erb`

- @ITurres: I have added the `delete` button to the `posts` show page.

#### `/app/views/posts/_post.html.erb`

- @demasameneshoa: I have added the `delete` button to the `posts` partial.

#### `/config/routes.rb`

- @ITurres && @demesameneshoa: We have added the `:destroy` action to the `resources :posts` and `resources :comments` routes.

#### `/db/schema.rb`

- @ITurres: regenerated the schema with the new user`role` column.

---

#### 🛑 Important Note: due to 3 commits having been pushed to `development` you might miss the changes done to `comments_controller.rb` in the PR diff. You can check the changes [here - commit #61ca4a2](https://github.com/ITurres/blog_app/commit/61ca4a2b871e717fbd507fe1cb9c971f1db00dec)

---

### CODE REVIEW

**Review by V-Blaze — CHANGES_REQUESTED** [review]
Hi @ITurres , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

dcentl8-9b96e129-9725-401b-ac34-2feb990202a0

## Invalid Code Review Request

## You have submitted a project, that does not have commits from your partners. This is a pair programming task and therefore each student need to contribute and commit to this branch.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ITurres** [comment]
Hi @V-Blaze! Thank you for your message! Given what you said, I will assume that you haven't read the full PR. If you kindly see the **Important Notes** made on it, I have mentioned that my coding partner has made changes and contributed to the project, but unfortunately, he committed those changes on the `development` branch, so we had to rebase it onto this branch, hence the changes diff aren't show here. 

🛑 Please refer to these links for his changes: 

- https://github.com/ITurres/blog_app/commit/61ca4a2b871e717fbd507fe1cb9c971f1db00dec
  - `comments_controller.rb` (not present in this PR) Added by @demesameneshoa.
- https://github.com/ITurres/blog_app/commit/6f2abef61cbd6a5654c4b91d3c8a7732c2d0a477
  - `routes.rb` (present in this PR due to the commits associated with the resolved merge conflicts.) but initially added by @demesameneshoa. 
- https://github.com/ITurres/blog_app/commit/c74f57778556bf9bad88c38f53b169e4588d04d0
  - `_posts.html.erb` (present in this PR due to the commits associated with the resolved merge conflicts.) but initially added by @demesameneshoa.

**Review by Shedrack-Sunday — APPROVED** [review]
Hi @ITurres and @demesameneshoa 👍 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

image

Highlights
- [x] Good project organization ✔️
- [x] Nice use of Rails  features  ✔️  
- [x] Kudus on implementing `admin` privilage professionally  👏 


Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by ITurres** [comment]
Hi @Shedrack-Sunday! Thank you for having reviewed and approved the PR 🤠! cheers!

**Pull request merged**
