### PR TITLE
Milestone 3: validation model spec

### PR DESCRIPTION
**Pull request by ITurres**
# 🚩I have made the following changes to complete Milestone 3

### Type of **`files`** changed/added

My Skills

### In this new Branch, I have **➕ADDED➕** the succeeding **\*📂 folders** and/or **\*\*📄 files** to complete this milestone [requirements](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_validations_model_spec.md)

# \*📂 root/

- ## \*📂 spec/

    - **\*\*📄 user_spec.rb** ➕
    - **\*\*📄 post_spec.rb** ➕

      - In both files, I tested the model's attribute validations and methods.
     
---

### I have **✏️MODIFIED✏️** the succeeding **\*📂 folders** and/or **📄\*\* files**

# \*📂 root/

- **\*\*📄 README.md** ✏️

  - I checked as completed the `Validations and Model specs` task.

- **\*\*📄 Gemfile** ✏️
- **\*\*📄 Gemfile.lock** ✏️

  - I installed the **rspec-rails** gem.

- ## \*📂 app/models/

    - **\*\*📄 user.rb** ✏️

      - I added the validations for the following attributes: `name` and `posts_counter`.

    - **\*\*📄 post.rb** ✏️

      - I added the validations for the following attributes: `title`, `comments_counter` and `likes_counter`.

---

### Thank you for taking the time to review this PR ⭐

---

If you need additional information or have any questions, please don't hesitate to contact me on Slack as _**Arturo (Arthur) Emanuel Guerra Iturres**_. I'll be happy to help you out. 🎯

---

### CODE REVIEW

**Review by mwanawabangona — CHANGES_REQUESTED** [review]
Hi @ITurres ,

Good job so far!

There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
* ✅  No linter errors :heavy_check_mark:
* ✅  Repo looks professional :briefcase:
* ✅  Good quality commits
* ✅  Strong Pull Request 


## Required Changes ♻️
_Check the comments under the review._

- [ ] Amazing job So far 👏 
- [ ] However  the requirements states that `Add unit specs for all of your models' methods and validations.`
- [ ] And you only Added tests for `post` and `user`.
- [ ] please add the remaining tests for `likes` and `comments` 🥂 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
-  Consider Running all the all unit Test  Before sending for the P.R

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ITurres** [comment]
Hi @mwanawabangona Ellis! Thank you for having reviewed this pr. you are absolutely right! I have overlooked that, maybe miss comprehended. Anyway, I'll make the changes right away ✨ thanks again!

**Review by FrederickMih — APPROVED** [review]
## Hi :raising_hand: :raising_hand: @ITurres, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 

:tada: :champagne:  :tada: :champagne: 

## Highlights :green_circle: 

- Nice job for adding both positive and negative validation tests for models :+1: 

## Optional suggestions
**N/A**

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ITurres** [comment]
Hi @FrederickMih! Thank you for the highlights :D. and cheers for approving the pr 🥂

**Pull request merged**
